apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 81
    targetPort: 8888
    nodePort: 30002    
  selector:
    app: demo