AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an EC2 instance with an ssh connection


Resources:
  LogicalID:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0533f2ba8a1995cf9
      InstanceType: t2.micro
      KeyName: bekir2
      SecurityGroups:
        - cfn-sec-group
      Tags:
        - Key: Name
          Value: cfn-sec-group

