apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: web-secrets-deploy
spec:
  replicas: 1 
  selector:  
    matchLabels:
      app: web-secrets
  minReadySeconds: 10 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1 
  template: 
    metadata:
      labels:
        app: web-secrets
        env: front-end
    spec:
      containers:
      - name: web-secrets-pod
        image: bkucukala/configmap:1.0
        ports:
        - containerPort: 5000