AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template creates an EC2 instance with an SSH connection.
  
Resources:
  SSHandHTTP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open ssh and http
      
      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      
     

  MyEC2Instance:

    Type: AWS::EC2::Instance

    Properties:

      ImageId: ami-0742b4e673072066f 

      InstanceType: t2.micro

      KeyName: bekir2

      SecurityGroups: 
        - !Ref SSHandHTTP

      Tags:
        - Key: Name
          Value: Web-Server-of-StackName
      
      UserData:
        Fn::Base64: |
          #!/bin/bash

          yum update -y
          yum install -y httpd
          
          cd /var/www/html  
          chmod -R 777 /var/www/html
          wget https://raw.githubusercontent.com/EserUsta/myProjects/main/kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/EserUsta/myProjects/main/kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/EserUsta/myProjects/main/kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/EserUsta/myProjects/main/kittens-carousel-static-website-ec2/static-web/index.html
          systemctl start httpd
          systemctl enable httpd
         